export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const LOAD_MOVIES_ERROR = "LOAD_MOVIES_ERROR";
export const LOAD_MOVIES_PENDING = "LOAD_MOVIES_PENDING";

export const LOAD_MOVIES_BY_GENRE_SUCCESS = "LOAD_MOVIES_BY_GENRE_SUCCESS";
export const LOAD_MOVIES_BY_GENRE_ERROR = "LOAD_MOVIES_BY_GENRE_ERROR";
export const LOAD_MOVIES_BY_GENRE_PENDING = "LOAD_MOVIES_BY_GENRE_PENDING";

export const LOAD_MOVIE_SUCCESS = "LOAD_MOVIE_SUCCESS";
export const LOAD_MOVIE_ERROR = "LOAD_MOVIE_ERROR";
export const LOAD_MOVIE_PENDING = "LOAD_MOVIE_PENDING";
